### ISSUE TITLE
Crash with EE3

### ISSUE THREAD

**Issue by VladimirMangos** [Funwayguy/RecipeResearch#6]
Minecraft crash for me if I add RecipeResearch-1.0.21.jar to mods list with EquivalentExchange3-1.7.10-0.3.507.jar with error:

 java.util.FormatFlagsConversionMismatchException: Conversion = c, Flags = 
at java.util.Formatter$FormatSpecifier.failMismatch(Unknown Source)
at java.util.Formatter$FormatSpecifier.checkBadFlags(Unknown Source)
at java.util.Formatter$FormatSpecifier.checkCharacter(Unknown Source)
at java.util.Formatter$FormatSpecifier.<init>(Unknown Source)
at java.util.Formatter.parse(Unknown Source)
at java.util.Formatter.format(Unknown Source)
at java.util.Formatter.format(Unknown Source)
at java.lang.String.format(Unknown Source)
at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:60)
at cpw.mods.fml.common.FMLLog.log(FMLLog.java:25)
at com.pahimar.ee3.util.LogHelper.log(LogHelper.java:11)
at com.pahimar.ee3.util.LogHelper.trace(LogHelper.java:46)
at com.pahimar.ee3.recipe.RecipeRegistry.addRecipe(RecipeRegistry.java:65)
at com.pahimar.ee3.api.exchange.RecipeRegistryProxy.addRecipe(RecipeRegistryProxy.java:17)

I think this is not EE3 problem because I not crash and play fine with EE3 amd mods without RecipeResearch

**Comment by Funwayguy** [comment]
This is likely an issue with EE3 trying to cache the recipes RecipeResearch has hidden. Turn off hiding recipes and it should work just fine.

**Comment by VladimirMangos** [comment]
Use [B:"Hide Recipes"=false] not help me with crash. Anyway thank you for clarify source of problem.

**Comment by lAminl** [comment]
hey vladimir, may i have any contacts with you? have some questions.

thanks

**Comment by VladimirMangos** [comment]
megatronir, you can ask me in PM at cmangos forum for example instead random discussion at github

**Comment by lAminl** [comment]
may you please give me the direct link of it?or what is your nickname in cmangos forum?
